version: 2.1

jobs:
  test-node:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test project
          command: npm test

  build-node:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Collect build artifacts
          command: |
            mkdir -p ~/artifacts
            for dir in build dist public .output .next .docusaurus; do
              [ -d "$dir" ] && cp -R "$dir" ~/artifacts/
            done
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
